import { Open_Sans } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { Toaster } from "@/components/ui/toaster";

const open_san = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={open_san.className + " bg-gray-50"}>
        <NextUIProvider>{children}</NextUIProvider>
        <Toaster />
      </body>
    </html>
  );
}
